baseURL: "https://TimS-ml.github.io/"
languageCode: "en-us"
title: "TimS's Machine Learning Blog"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Enable search
outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  env: production  # Enable google analytics, opengraph and other features
  description: "A blog about Machine Learning and AI"  # Important SEO description
  keywords: ["Machine Learning", "AI", "Math", "Entrepreneurship", "Blog"]
  author: "TimS"
  DateFormat: "January 2, 2006"

  # Basic Settings
  defaultTheme: light
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true

  # Home Page Settings
  profileMode:
    enabled: true
    title: "TimS's Blog on AI, Math and Entrepreneurship"
    subtitle: "Where there is a will, there is a way."
    imageUrl: "profile.png"

  # Recommended social media links
  socialIcons:
    - name: "github"
      url: "https://github.com/TimS-ml"
    - name: "x"
      url: "https://x.com/Jxueba"
    # - name: "linkedin"
    #   url: "your LinkedIn link"

  # # Homepage info settings (if not using profileMode)
  # homeInfoParams:
  #   Title: "Welcome to TimS's Blog 👋"
  #   Content: "Exploring AI, Math and Entrepreneurship"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Main menu configuration
menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 10
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 20
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

# Code highlighting settings
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

pagination:
  pagerSize: 5
