baseURL = "https://TimS-ml.github.io/"
languageCode = "en-us"
title = "Tim's Machine Learning Blog"
theme = "PaperMod"

# Enable search
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
# Basic Settings
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

# Home Page Settings
profileMode = true

[params.profileMode]
enabled = true
title = "Tim's Machine Learning Blog"
subtitle = "Exploring AI, Machine Learning, and Data Science"
imageUrl = "profile.jpg"  # Add your profile image to static folder
